server.port=${PORT:8080}

spring.application.name=backend
spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/etayodb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (In production this would be an env variable)
jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b2a7585f67b557fb40b3ec56a5dc8172df}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Google Drive API OAuth 2.0 Credentials
google.drive.client.id=${GOOGLE_DRIVE_CLIENT_ID:}
google.drive.client.secret=${GOOGLE_DRIVE_CLIENT_SECRET:}
google.drive.refresh.token=${GOOGLE_DRIVE_REFRESH_TOKEN:}
google.drive.folder.id=${GOOGLE_DRIVE_FOLDER_ID:}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

